version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: resource_tracker_db
    environment:
      POSTGRES_DB: resource_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Shakti!1997
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Main data directory
      - postgres_data:/var/lib/postgresql/data
      # Optional: Custom init scripts
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d resource_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: resource_tracker_data
    driver: local

networks:
  default:
    name: resource_tracker_network